### ISSUE TITLE
TypeError: entity-schema claim parser isn't implemented

### ISSUE THREAD

**Issue by Yajha** [maxlath/wikibase-dump-filter#43]
Hi , found a problem when using **--simplify** .

- wikibase-dump-filter version: 5.0.7
- NodeJS version: v12.22.1
- OS version: CentOS Linux release 7.9.2009 (Core)

Reproduction:
**cat latest-all.json.gz | gzip -d | wikibase-dump-filter --simplify  > simplified_wikidata.ndjson**

Error:
modules/wikibase-sdk/lib/helpers/parse_claim.js:116
      throw err
      ^

TypeError: entity-schema claim parser isn't implemented
        Claim id: Q8502$ccf20476-492b-da1f-a726-fb29f295bc69
        Please report to https://github.com/maxlath/wikibase-sdk/issues
    at parse (/usr/local/lib/node_modules/wikibase-dump-filter/node_modules/wikibase-sdk/lib/helpers/parse_claim.js:109:31)
    at simplifyClaim (/usr/local/lib/node_modules/wikibase-dump-filter/node_modules/wikibase-sdk/lib/helpers/simplify_claims.js:79:13)
    at /usr/local/lib/node_modules/wikibase-dump-filter/node_modules/wikibase-sdk/lib/helpers/simplify_claims.js:37:19
    at Array.map (<anonymous>)
    at simplifyPropertyClaims (/usr/local/lib/node_modules/wikibase-dump-filter/node_modules/wikibase-sdk/lib/helpers/simplify_claims.js:37:6)
    at Object.simplifyClaims (/usr/local/lib/node_modules/wikibase-dump-filter/node_modules/wikibase-sdk/lib/helpers/simplify_claims.js:15:24)
    at simplifyIfDefined (/usr/local/lib/node_modules/wikibase-dump-filter/node_modules/wikibase-sdk/lib/helpers/simplify_entity.js:39:48)
    at simplifyEntity (/usr/local/lib/node_modules/wikibase-dump-filter/node_modules/wikibase-sdk/lib/helpers/simplify_entity.js:17:5)
    at /usr/local/lib/node_modules/wikibase-dump-filter/lib/format_entity.js:31:16
    at /usr/local/lib/node_modules/wikibase-dump-filter/lib/filter_format_and_serialize_entity.js:18:30

just wonder what causes this problem.
Thanks for your time.

**Comment by maxlath** [comment]
Ah yes, support for the new `entity-schema` type was missing; that should now be fixed in `v6.0.0`, after having updated `wikibase-sdk > v10.1.0`. I would assume this is fixed, but you are welcome to re-open the issue if it isn't.
